/**
 * @description       : EC_Constants
 * @author            : hegoswami@deloitte.com
 * @group             : 
 * @last modified on  : 11-05-2024
 * @last modified by  : hegoswami@deloitte.com
**/
public class EC_Constants {

    public final static String FCTL_STORE='Final Control';
    public final static String MSOL_STORE='Measurement Instrumentation';
    public final static String FCTL_PDP_FIELDSET='EC_FCTL_fields';

}