/**
 * @description       : EC_Constants
 * @author            : hegoswami@deloitte.com
 * @group             : 
 * @last modified on  : 11-06-2024
 * @last modified by  : hegoswami@deloitte.com
**/
public class EC_Constants {

    public final static String FCTL_STORE='Final Control';
    public final static String MSOL_STORE='Measurement Instrumentation';
    public final static String FCTL_PDP_FIELDSET='EC_FCTL_fields';
    public final static String API_CONTENT_TYPE='Content-Type';
    public final static String API_CONTENT_TYPE_VALUE_JSON='application/x-www-form-urlencoded';
    public final static String API_METHOD_POST='POST';
    public final static String SYSS_STORE = 'Systems & Software';
    public final static String PRODUCT_DETAIL_KEY = 'productDetails';
    public final static String PRODUCT_SERVICES = '/webruntime/api/services/data/v62.0/commerce/webstores/';
    public final static String MSOL_SITE_NAME = 'MeasurementInstrumentation';
    public final static String PRODUCTS = '/products/';
    public final static String API_METHOD_GET = 'GET';
    public final static String API_CONTENT_TYPE_JSON = 'application/json';

}